// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RewardPacket.proto

package kr.ac.mju.islab;

public final class RewardProto {
  private RewardProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RewardPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:reward.RewardPacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 pid = 1;</code>
     */
    int getPid();

    /**
     * <code>optional bool isValid = 2;</code>
     */
    boolean getIsValid();

    /**
     * <code>optional bytes e1 = 3;</code>
     */
    com.google.protobuf.ByteString getE1();

    /**
     * <code>optional bytes e2 = 4;</code>
     */
    com.google.protobuf.ByteString getE2();

    /**
     * <code>optional bytes e3 = 5;</code>
     */
    com.google.protobuf.ByteString getE3();

    /**
     * <code>repeated bytes eList1 = 6;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getEList1List();
    /**
     * <code>repeated bytes eList1 = 6;</code>
     */
    int getEList1Count();
    /**
     * <code>repeated bytes eList1 = 6;</code>
     */
    com.google.protobuf.ByteString getEList1(int index);

    /**
     * <code>repeated bytes eList2 = 7;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getEList2List();
    /**
     * <code>repeated bytes eList2 = 7;</code>
     */
    int getEList2Count();
    /**
     * <code>repeated bytes eList2 = 7;</code>
     */
    com.google.protobuf.ByteString getEList2(int index);

    /**
     * <code>repeated string aux = 8;</code>
     */
    java.util.List<java.lang.String>
        getAuxList();
    /**
     * <code>repeated string aux = 8;</code>
     */
    int getAuxCount();
    /**
     * <code>repeated string aux = 8;</code>
     */
    java.lang.String getAux(int index);
    /**
     * <code>repeated string aux = 8;</code>
     */
    com.google.protobuf.ByteString
        getAuxBytes(int index);
  }
  /**
   * Protobuf type {@code reward.RewardPacket}
   */
  public  static final class RewardPacket extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:reward.RewardPacket)
      RewardPacketOrBuilder {
    // Use RewardPacket.newBuilder() to construct.
    private RewardPacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RewardPacket() {
      pid_ = 0;
      isValid_ = false;
      e1_ = com.google.protobuf.ByteString.EMPTY;
      e2_ = com.google.protobuf.ByteString.EMPTY;
      e3_ = com.google.protobuf.ByteString.EMPTY;
      eList1_ = java.util.Collections.emptyList();
      eList2_ = java.util.Collections.emptyList();
      aux_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RewardPacket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              pid_ = input.readInt32();
              break;
            }
            case 16: {

              isValid_ = input.readBool();
              break;
            }
            case 26: {

              e1_ = input.readBytes();
              break;
            }
            case 34: {

              e2_ = input.readBytes();
              break;
            }
            case 42: {

              e3_ = input.readBytes();
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                eList1_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000020;
              }
              eList1_.add(input.readBytes());
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                eList2_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000040;
              }
              eList2_.add(input.readBytes());
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
                aux_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000080;
              }
              aux_.add(s);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          eList1_ = java.util.Collections.unmodifiableList(eList1_);
        }
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          eList2_ = java.util.Collections.unmodifiableList(eList2_);
        }
        if (((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
          aux_ = aux_.getUnmodifiableView();
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return kr.ac.mju.islab.RewardProto.internal_static_reward_RewardPacket_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return kr.ac.mju.islab.RewardProto.internal_static_reward_RewardPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              kr.ac.mju.islab.RewardProto.RewardPacket.class, kr.ac.mju.islab.RewardProto.RewardPacket.Builder.class);
    }

    private int bitField0_;
    public static final int PID_FIELD_NUMBER = 1;
    private int pid_;
    /**
     * <code>optional int32 pid = 1;</code>
     */
    public int getPid() {
      return pid_;
    }

    public static final int ISVALID_FIELD_NUMBER = 2;
    private boolean isValid_;
    /**
     * <code>optional bool isValid = 2;</code>
     */
    public boolean getIsValid() {
      return isValid_;
    }

    public static final int E1_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString e1_;
    /**
     * <code>optional bytes e1 = 3;</code>
     */
    public com.google.protobuf.ByteString getE1() {
      return e1_;
    }

    public static final int E2_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString e2_;
    /**
     * <code>optional bytes e2 = 4;</code>
     */
    public com.google.protobuf.ByteString getE2() {
      return e2_;
    }

    public static final int E3_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString e3_;
    /**
     * <code>optional bytes e3 = 5;</code>
     */
    public com.google.protobuf.ByteString getE3() {
      return e3_;
    }

    public static final int ELIST1_FIELD_NUMBER = 6;
    private java.util.List<com.google.protobuf.ByteString> eList1_;
    /**
     * <code>repeated bytes eList1 = 6;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getEList1List() {
      return eList1_;
    }
    /**
     * <code>repeated bytes eList1 = 6;</code>
     */
    public int getEList1Count() {
      return eList1_.size();
    }
    /**
     * <code>repeated bytes eList1 = 6;</code>
     */
    public com.google.protobuf.ByteString getEList1(int index) {
      return eList1_.get(index);
    }

    public static final int ELIST2_FIELD_NUMBER = 7;
    private java.util.List<com.google.protobuf.ByteString> eList2_;
    /**
     * <code>repeated bytes eList2 = 7;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getEList2List() {
      return eList2_;
    }
    /**
     * <code>repeated bytes eList2 = 7;</code>
     */
    public int getEList2Count() {
      return eList2_.size();
    }
    /**
     * <code>repeated bytes eList2 = 7;</code>
     */
    public com.google.protobuf.ByteString getEList2(int index) {
      return eList2_.get(index);
    }

    public static final int AUX_FIELD_NUMBER = 8;
    private com.google.protobuf.LazyStringList aux_;
    /**
     * <code>repeated string aux = 8;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getAuxList() {
      return aux_;
    }
    /**
     * <code>repeated string aux = 8;</code>
     */
    public int getAuxCount() {
      return aux_.size();
    }
    /**
     * <code>repeated string aux = 8;</code>
     */
    public java.lang.String getAux(int index) {
      return aux_.get(index);
    }
    /**
     * <code>repeated string aux = 8;</code>
     */
    public com.google.protobuf.ByteString
        getAuxBytes(int index) {
      return aux_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (pid_ != 0) {
        output.writeInt32(1, pid_);
      }
      if (isValid_ != false) {
        output.writeBool(2, isValid_);
      }
      if (!e1_.isEmpty()) {
        output.writeBytes(3, e1_);
      }
      if (!e2_.isEmpty()) {
        output.writeBytes(4, e2_);
      }
      if (!e3_.isEmpty()) {
        output.writeBytes(5, e3_);
      }
      for (int i = 0; i < eList1_.size(); i++) {
        output.writeBytes(6, eList1_.get(i));
      }
      for (int i = 0; i < eList2_.size(); i++) {
        output.writeBytes(7, eList2_.get(i));
      }
      for (int i = 0; i < aux_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, aux_.getRaw(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (pid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, pid_);
      }
      if (isValid_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, isValid_);
      }
      if (!e1_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, e1_);
      }
      if (!e2_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, e2_);
      }
      if (!e3_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, e3_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < eList1_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(eList1_.get(i));
        }
        size += dataSize;
        size += 1 * getEList1List().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < eList2_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(eList2_.get(i));
        }
        size += dataSize;
        size += 1 * getEList2List().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < aux_.size(); i++) {
          dataSize += computeStringSizeNoTag(aux_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getAuxList().size();
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof kr.ac.mju.islab.RewardProto.RewardPacket)) {
        return super.equals(obj);
      }
      kr.ac.mju.islab.RewardProto.RewardPacket other = (kr.ac.mju.islab.RewardProto.RewardPacket) obj;

      boolean result = true;
      result = result && (getPid()
          == other.getPid());
      result = result && (getIsValid()
          == other.getIsValid());
      result = result && getE1()
          .equals(other.getE1());
      result = result && getE2()
          .equals(other.getE2());
      result = result && getE3()
          .equals(other.getE3());
      result = result && getEList1List()
          .equals(other.getEList1List());
      result = result && getEList2List()
          .equals(other.getEList2List());
      result = result && getAuxList()
          .equals(other.getAuxList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + PID_FIELD_NUMBER;
      hash = (53 * hash) + getPid();
      hash = (37 * hash) + ISVALID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsValid());
      hash = (37 * hash) + E1_FIELD_NUMBER;
      hash = (53 * hash) + getE1().hashCode();
      hash = (37 * hash) + E2_FIELD_NUMBER;
      hash = (53 * hash) + getE2().hashCode();
      hash = (37 * hash) + E3_FIELD_NUMBER;
      hash = (53 * hash) + getE3().hashCode();
      if (getEList1Count() > 0) {
        hash = (37 * hash) + ELIST1_FIELD_NUMBER;
        hash = (53 * hash) + getEList1List().hashCode();
      }
      if (getEList2Count() > 0) {
        hash = (37 * hash) + ELIST2_FIELD_NUMBER;
        hash = (53 * hash) + getEList2List().hashCode();
      }
      if (getAuxCount() > 0) {
        hash = (37 * hash) + AUX_FIELD_NUMBER;
        hash = (53 * hash) + getAuxList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static kr.ac.mju.islab.RewardProto.RewardPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kr.ac.mju.islab.RewardProto.RewardPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kr.ac.mju.islab.RewardProto.RewardPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kr.ac.mju.islab.RewardProto.RewardPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kr.ac.mju.islab.RewardProto.RewardPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static kr.ac.mju.islab.RewardProto.RewardPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static kr.ac.mju.islab.RewardProto.RewardPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static kr.ac.mju.islab.RewardProto.RewardPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static kr.ac.mju.islab.RewardProto.RewardPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static kr.ac.mju.islab.RewardProto.RewardPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(kr.ac.mju.islab.RewardProto.RewardPacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code reward.RewardPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:reward.RewardPacket)
        kr.ac.mju.islab.RewardProto.RewardPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return kr.ac.mju.islab.RewardProto.internal_static_reward_RewardPacket_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return kr.ac.mju.islab.RewardProto.internal_static_reward_RewardPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                kr.ac.mju.islab.RewardProto.RewardPacket.class, kr.ac.mju.islab.RewardProto.RewardPacket.Builder.class);
      }

      // Construct using kr.ac.mju.islab.RewardProto.RewardPacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        pid_ = 0;

        isValid_ = false;

        e1_ = com.google.protobuf.ByteString.EMPTY;

        e2_ = com.google.protobuf.ByteString.EMPTY;

        e3_ = com.google.protobuf.ByteString.EMPTY;

        eList1_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        eList2_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        aux_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return kr.ac.mju.islab.RewardProto.internal_static_reward_RewardPacket_descriptor;
      }

      public kr.ac.mju.islab.RewardProto.RewardPacket getDefaultInstanceForType() {
        return kr.ac.mju.islab.RewardProto.RewardPacket.getDefaultInstance();
      }

      public kr.ac.mju.islab.RewardProto.RewardPacket build() {
        kr.ac.mju.islab.RewardProto.RewardPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public kr.ac.mju.islab.RewardProto.RewardPacket buildPartial() {
        kr.ac.mju.islab.RewardProto.RewardPacket result = new kr.ac.mju.islab.RewardProto.RewardPacket(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.pid_ = pid_;
        result.isValid_ = isValid_;
        result.e1_ = e1_;
        result.e2_ = e2_;
        result.e3_ = e3_;
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          eList1_ = java.util.Collections.unmodifiableList(eList1_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.eList1_ = eList1_;
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          eList2_ = java.util.Collections.unmodifiableList(eList2_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.eList2_ = eList2_;
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          aux_ = aux_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000080);
        }
        result.aux_ = aux_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof kr.ac.mju.islab.RewardProto.RewardPacket) {
          return mergeFrom((kr.ac.mju.islab.RewardProto.RewardPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(kr.ac.mju.islab.RewardProto.RewardPacket other) {
        if (other == kr.ac.mju.islab.RewardProto.RewardPacket.getDefaultInstance()) return this;
        if (other.getPid() != 0) {
          setPid(other.getPid());
        }
        if (other.getIsValid() != false) {
          setIsValid(other.getIsValid());
        }
        if (other.getE1() != com.google.protobuf.ByteString.EMPTY) {
          setE1(other.getE1());
        }
        if (other.getE2() != com.google.protobuf.ByteString.EMPTY) {
          setE2(other.getE2());
        }
        if (other.getE3() != com.google.protobuf.ByteString.EMPTY) {
          setE3(other.getE3());
        }
        if (!other.eList1_.isEmpty()) {
          if (eList1_.isEmpty()) {
            eList1_ = other.eList1_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureEList1IsMutable();
            eList1_.addAll(other.eList1_);
          }
          onChanged();
        }
        if (!other.eList2_.isEmpty()) {
          if (eList2_.isEmpty()) {
            eList2_ = other.eList2_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureEList2IsMutable();
            eList2_.addAll(other.eList2_);
          }
          onChanged();
        }
        if (!other.aux_.isEmpty()) {
          if (aux_.isEmpty()) {
            aux_ = other.aux_;
            bitField0_ = (bitField0_ & ~0x00000080);
          } else {
            ensureAuxIsMutable();
            aux_.addAll(other.aux_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        kr.ac.mju.islab.RewardProto.RewardPacket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (kr.ac.mju.islab.RewardProto.RewardPacket) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int pid_ ;
      /**
       * <code>optional int32 pid = 1;</code>
       */
      public int getPid() {
        return pid_;
      }
      /**
       * <code>optional int32 pid = 1;</code>
       */
      public Builder setPid(int value) {
        
        pid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 pid = 1;</code>
       */
      public Builder clearPid() {
        
        pid_ = 0;
        onChanged();
        return this;
      }

      private boolean isValid_ ;
      /**
       * <code>optional bool isValid = 2;</code>
       */
      public boolean getIsValid() {
        return isValid_;
      }
      /**
       * <code>optional bool isValid = 2;</code>
       */
      public Builder setIsValid(boolean value) {
        
        isValid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool isValid = 2;</code>
       */
      public Builder clearIsValid() {
        
        isValid_ = false;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString e1_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes e1 = 3;</code>
       */
      public com.google.protobuf.ByteString getE1() {
        return e1_;
      }
      /**
       * <code>optional bytes e1 = 3;</code>
       */
      public Builder setE1(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        e1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes e1 = 3;</code>
       */
      public Builder clearE1() {
        
        e1_ = getDefaultInstance().getE1();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString e2_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes e2 = 4;</code>
       */
      public com.google.protobuf.ByteString getE2() {
        return e2_;
      }
      /**
       * <code>optional bytes e2 = 4;</code>
       */
      public Builder setE2(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        e2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes e2 = 4;</code>
       */
      public Builder clearE2() {
        
        e2_ = getDefaultInstance().getE2();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString e3_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes e3 = 5;</code>
       */
      public com.google.protobuf.ByteString getE3() {
        return e3_;
      }
      /**
       * <code>optional bytes e3 = 5;</code>
       */
      public Builder setE3(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        e3_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes e3 = 5;</code>
       */
      public Builder clearE3() {
        
        e3_ = getDefaultInstance().getE3();
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> eList1_ = java.util.Collections.emptyList();
      private void ensureEList1IsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          eList1_ = new java.util.ArrayList<com.google.protobuf.ByteString>(eList1_);
          bitField0_ |= 0x00000020;
         }
      }
      /**
       * <code>repeated bytes eList1 = 6;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getEList1List() {
        return java.util.Collections.unmodifiableList(eList1_);
      }
      /**
       * <code>repeated bytes eList1 = 6;</code>
       */
      public int getEList1Count() {
        return eList1_.size();
      }
      /**
       * <code>repeated bytes eList1 = 6;</code>
       */
      public com.google.protobuf.ByteString getEList1(int index) {
        return eList1_.get(index);
      }
      /**
       * <code>repeated bytes eList1 = 6;</code>
       */
      public Builder setEList1(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureEList1IsMutable();
        eList1_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes eList1 = 6;</code>
       */
      public Builder addEList1(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureEList1IsMutable();
        eList1_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes eList1 = 6;</code>
       */
      public Builder addAllEList1(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureEList1IsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, eList1_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes eList1 = 6;</code>
       */
      public Builder clearEList1() {
        eList1_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> eList2_ = java.util.Collections.emptyList();
      private void ensureEList2IsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          eList2_ = new java.util.ArrayList<com.google.protobuf.ByteString>(eList2_);
          bitField0_ |= 0x00000040;
         }
      }
      /**
       * <code>repeated bytes eList2 = 7;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getEList2List() {
        return java.util.Collections.unmodifiableList(eList2_);
      }
      /**
       * <code>repeated bytes eList2 = 7;</code>
       */
      public int getEList2Count() {
        return eList2_.size();
      }
      /**
       * <code>repeated bytes eList2 = 7;</code>
       */
      public com.google.protobuf.ByteString getEList2(int index) {
        return eList2_.get(index);
      }
      /**
       * <code>repeated bytes eList2 = 7;</code>
       */
      public Builder setEList2(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureEList2IsMutable();
        eList2_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes eList2 = 7;</code>
       */
      public Builder addEList2(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureEList2IsMutable();
        eList2_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes eList2 = 7;</code>
       */
      public Builder addAllEList2(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureEList2IsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, eList2_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes eList2 = 7;</code>
       */
      public Builder clearEList2() {
        eList2_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList aux_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureAuxIsMutable() {
        if (!((bitField0_ & 0x00000080) == 0x00000080)) {
          aux_ = new com.google.protobuf.LazyStringArrayList(aux_);
          bitField0_ |= 0x00000080;
         }
      }
      /**
       * <code>repeated string aux = 8;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getAuxList() {
        return aux_.getUnmodifiableView();
      }
      /**
       * <code>repeated string aux = 8;</code>
       */
      public int getAuxCount() {
        return aux_.size();
      }
      /**
       * <code>repeated string aux = 8;</code>
       */
      public java.lang.String getAux(int index) {
        return aux_.get(index);
      }
      /**
       * <code>repeated string aux = 8;</code>
       */
      public com.google.protobuf.ByteString
          getAuxBytes(int index) {
        return aux_.getByteString(index);
      }
      /**
       * <code>repeated string aux = 8;</code>
       */
      public Builder setAux(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAuxIsMutable();
        aux_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string aux = 8;</code>
       */
      public Builder addAux(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAuxIsMutable();
        aux_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string aux = 8;</code>
       */
      public Builder addAllAux(
          java.lang.Iterable<java.lang.String> values) {
        ensureAuxIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, aux_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string aux = 8;</code>
       */
      public Builder clearAux() {
        aux_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string aux = 8;</code>
       */
      public Builder addAuxBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureAuxIsMutable();
        aux_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:reward.RewardPacket)
    }

    // @@protoc_insertion_point(class_scope:reward.RewardPacket)
    private static final kr.ac.mju.islab.RewardProto.RewardPacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new kr.ac.mju.islab.RewardProto.RewardPacket();
    }

    public static kr.ac.mju.islab.RewardProto.RewardPacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RewardPacket>
        PARSER = new com.google.protobuf.AbstractParser<RewardPacket>() {
      public RewardPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RewardPacket(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RewardPacket> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RewardPacket> getParserForType() {
      return PARSER;
    }

    public kr.ac.mju.islab.RewardProto.RewardPacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reward_RewardPacket_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reward_RewardPacket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022RewardPacket.proto\022\006reward\"}\n\014RewardPa" +
      "cket\022\013\n\003pid\030\001 \001(\005\022\017\n\007isValid\030\002 \001(\010\022\n\n\002e1" +
      "\030\003 \001(\014\022\n\n\002e2\030\004 \001(\014\022\n\n\002e3\030\005 \001(\014\022\016\n\006eList1" +
      "\030\006 \003(\014\022\016\n\006eList2\030\007 \003(\014\022\013\n\003aux\030\010 \003(\tB\036\n\017k" +
      "r.ac.mju.islabB\013RewardProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_reward_RewardPacket_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_reward_RewardPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reward_RewardPacket_descriptor,
        new java.lang.String[] { "Pid", "IsValid", "E1", "E2", "E3", "EList1", "EList2", "Aux", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
